set(_CATKIN_CURRENT_PACKAGE "odometry_source")
set(odometry_source_MAINTAINER "ceezeh <ceezeh@todo.todo>")
set(odometry_source_DEPRECATED "")
set(odometry_source_VERSION "0.0.0")
set(odometry_source_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(odometry_source_RUN_DEPENDS "geometry_msgs" "tf" "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(odometry_source_BUILDTOOL_DEPENDS "catkin")