set(_CATKIN_CURRENT_PACKAGE "laser_geometry")
set(laser_geometry_VERSION "1.5.15")
set(laser_geometry_MAINTAINER "Dave Hershberger <hersh@willowgarage.com>")
set(laser_geometry_BUILD_DEPENDS "sensor_msgs" "roscpp" "tf" "angles" "eigen" "boost")
set(laser_geometry_RUN_DEPENDS "sensor_msgs" "roscpp" "tf" "angles" "eigen" "boost")
set(laser_geometry_DEPRECATED "")
set(laser_geometry_BUILDTOOL_DEPENDS "catkin")
set(laser_geometry_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")